-- This script was generated by the ERD tool in pgAdmin 4.
COMMENT ON SCHEMA public IS 'standard public schema';

GRANT USAGE ON SCHEMA public TO PUBLIC;

GRANT ALL ON SCHEMA public TO pg_database_owner;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";